In [1]:
import torch

In [6]:
x = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])
index = torch.LongTensor([0,1,1])
i = torch.LongTensor([0,1,2])
print(x[i,index])

tensor([1, 5, 8])


In [9]:
torch.arange(0,3,1)

tensor([0, 1, 2])

In [10]:
x = torch.tensor([1,2,3])
y = torch.tensor([0,1,1,2,1,0])
print(x[y])

tensor([1, 2, 2, 3, 2, 1])
